name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: 업무일지 대신 작성해주기 
      id: worklog
      uses: opentutorials-org/action-airtable-worklog@v1.0.6
      with:
        AIRTABLE_SECRET: ${{ secrets.AIRTABLE_SECRET }} 
        AIRTABLE_BASE: ${{ secrets.AIRTABLE_BASE }} 
